### ISSUE TITLE
Need Open Brands dataset to run the sample code

### ISSUE THREAD

**Issue by dmvictor** [FenHua/Robust_Logo_Detection#2]
I tried to run [test_sample.sh](https://github.com/FenHua/Robust_Logo_Detection/blob/master/test_sample.sh) with the pretrained model, which got some errors. The error message showed OpenBrandDataset not found. 

Hence, I tried to download the dataset from [ACM MM2021 Security AI Challenger](https://tianchi.aliyun.com/competition/entrance/531888/information), but the site popped up a message showing "You should register this competition before downloading the dataset". I don't think I could register for the competition now.

Could you provide the dataset for running the example? Thank you!

**Comment by FenHua** [comment]
Hi, I added the download path file *.md, but I'm not sure if these download links are working, hope they are useful for you. Thank you!

**Comment by dmvictor** [comment]
Thanks for your response. The links worked with Microsoft Edge browser. I could not download the dataset with Google Chrome and Vivaldi browser. After some trials, I figured out some browsers will not be allowed to download the zip files for security issues.
