### ISSUE TITLE
可否提供少量数据集用于测试？

### ISSUE THREAD

**Issue by DWCTOD** [FenHua/Robust_Logo_Detection#6]
你好，根据项目中提供的下载链接，无法下载训练的json文件，不知道是否可以提供其他的下载方法，我想用来测试一下，谢谢啦～期待大佬的回复

**Comment by FenHua** [comment]
https://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/531888/openbrand_train.json  这个脚本可以打开，你保存成json即可

**Comment by DWCTOD** [comment]
好的，谢谢大佬
