### ISSUE TITLE
Min image size?

### ISSUE THREAD

**Issue by Charlyo** [FenHua/Robust_Logo_Detection#8]
Trying with several different sized images, found the following error in some of them:

Padding size should be less than the corresponding input dimension, but got: padding (2, 2) at dimension 2 of input [1, 512, 2, 42]

Can you please elaborate in the minimum image size? 

Thank you

**Comment by FenHua** [comment]
[(1333, 800), (1333, 900), (1333, 1000), (1333, 1100)]

**Comment by Charlyo** [comment]
Thanks!
